### ISSUE TITLE
Magento 2.3

### ISSUE THREAD

**Issue by rommelfreddy** [staempfli/magento2-module-cookie-consent#3]
This extension is still not compatible with magento 2.3

**Comment by audef1** [comment]
Feel free and create a pull request ;)

**Comment by rommelfreddy** [comment]
i have already created an pull request but nobody approved it ... i guess cause the failed automated tests.

**Comment by rommelfreddy** [comment]
push!

**Comment by mhauri** [comment]
Solved in #4
Thank you for your contribution.
